version: "3.3"
services:
  web:
    image: php:7.3-apache
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php73
    stdin_open: true
    tty: true
    volumes:
      - .:/var/www/html/
    ports:
      - 8000:80
      - 8001:443
    networks:
      app-network:
        ipv4_address: 172.20.0.6
  db:
    container_name: mysql
    image: mysql:5.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password --sql_mode="" --max_allowed_packet=32505856
    volumes:
      - .:/var/www/html/
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: pj_integrador
    ports:
      - 3306:3306
    cap_add:
      - SYS_NICE
    security_opt:
      - seccomp:unconfined

  phpmyadmin2:
    container_name: phpmyadmin2
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - db
    ports:
      - 8082:80
    environment:
      PMA_HOST: db

networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
